server:
  port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/react_practice?useSSL=false&serverTimezone=UTC
    username: root
    password: Ramu@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true